spring:
  application:
    name: modulith-emp
  modulith:
    

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:modulith_emp}
    username: ${POSTGRES_USER:wpfeiffe}
    password: ${POSTGRES_PASSWORD:Password1}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  sql:
    init:
      mode: always
  jpa:
    show-sql: false
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
